env:
  JULIA_VERSION: "1.9.0"
  OPENMPI_VERSION: "4.0.4"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"
  GKSwstype: 100

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1

steps:
  - label: "init environment :computer:"
    key: "init_cpu_env"
    command:

      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - "julia --project=experiments -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments -e 'using Pkg; Pkg.status()'"

  - wait

  - group: "Experiments"
    steps:
      - label: "Richards comparison to Bonan"
        command: "julia --color=yes --project=experiments experiments/standalone/Soil/richards_comparison.jl"
        artifact_paths: "experiments/standalone/Soil/comparison*png"

      - label: "Evaporation from sand"
        command: "julia --color=yes --project=experiments experiments/standalone/Soil/evaporation.jl"
        artifact_paths: "experiments/standalone/Soil/evaporation*png"

      - label: "ozark_test_hydrology_only"
        command: "julia --color=yes --project=experiments experiments/integrated/ozark/hydrology_only/ozark.jl"
        artifact_paths: "experiments/integrated/ozark/hydrology_only/*png"

      - label: "ozark_test"
        command: "julia --color=yes --project=experiments experiments/integrated/ozark/ozark.jl"
        artifact_paths: "experiments/integrated/ozark/*png"

      - label: "ozark_conservation"
        command: "julia --color=yes --project=experiments experiments/integrated/ozark/conservation/ozark_conservation.jl"
        artifact_paths: "experiments/integrated/ozark/conservation/*png"

      - label: "Soilbiogeochem"
        command: "julia --color=yes --project=experiments experiments/standalone/Biogeochemistry/experiment.jl"

      - label: "Water conservation"
        command: "julia --color=yes --project=experiments experiments/standalone/Soil/water_conservation.jl"
        artifact_paths: "experiments/standalone/Soil/water_conservation*png"
