env:
  JULIA_VERSION: "1.8.1"
  OPENMPI_VERSION: "4.0.4"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1

steps:
  - label: "init environment :computer:"
    key: "init_cpu_env"
    command:
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - "julia --project=test -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=test -e 'using Pkg; Pkg.status()'"

      - "julia --project=experiments -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments -e 'using Pkg; Pkg.status()'"
      
  - wait

  - group: "Unit tests"
    steps:

      - label: "regridder"
        command: "julia --color=yes --project=test test/Bucket/regridder.jl"
        artifact_paths: "regridder/"

      - label: "albedo_map"
        command: "julia --color=yes --project=test test/Bucket/albedo_map_bucket.jl"
        artifact_paths: "albedo_map/"

      - label: "Richards comparison to Bonan"
        command: "julia --color=yes --project=experiments experiments/Soil/richards_comparison.jl"
        artifact_paths: "experiments/Soil/*png"

      - label: "ozark_test"
        command: "julia --color=yes --project=experiments experiments/LSM/ozark_test.jl"
        artifact_paths: "experiments/LSM/"

      - label: "Soilbiogeochem"
        command: "julia --color=yes --project=experiments experiments/Biogeochemistry/experiment.jl"